### ISSUE TITLE
Could provide some binary release for easy testing?

### ISSUE THREAD

**Issue by oscarbg** [Xaymar/ffmpeg-amf#1]

**Comment by Xaymar** [comment]
Binary releases will be provided by ffmpeg once it is included. For now you will have to either build it yourself or find someone that builds these for you.

**Comment by MikhailAMD** [comment]
FFmpeg-AMF integration was pushed to FFmpeg git tree. Unfortunately FFmpeg team refused to include AMF headers so AMF is not enabled in the default FFmpeg build. To enable it, binary builders should pull AMF headers from AMF GitHub. The headers where recently updated to work with FFmpeg. Ask the binary builders like Zeranoe to get the headers or advocate FFmpeg team to include them.

**Comment by Xaymar** [comment]
Early ffmpeg-amf builds are available on Patreon: https://www.patreon.com/posts/situation-with-15434421. Builds will later be available to the public (9th Dec for that one).

While I do not agree with the decision to exclude the AMD header, it's at least good to see that they finally gave in and accepted the main patch. I hope that ffmpeg will also exclude all other third party headers, as otherwise this gives other vendors a big market advantage, which is just not okay (both legally and morally).

**Comment by oscarbg** [comment]
So today is the day the build is posted here?

**Comment by Xaymar** [comment]
@oscarbg In ~1 hour the linked post above should automatically switch to be available for everyone.

**Comment by oscarbg** [comment]
thanks!

**Comment by oscarbg** [comment]
Hi,
just testing seems ffmpeg.exe fails to launch.. 
it seems for people without Mingw64 installed is missing:
libwinpthread-1.dll
libz-1.dll
libraries..
I installed MingW64 and still doesn't ship with libz-1.dll by default..

**Comment by Xaymar** [comment]
Release 3.4 has everything necessary. Additionally, those libraries are included in the Windows 10 Linux Support Toolset, or shipped by MSYS2 MingW64.

**Comment by Xaymar** [comment]
Zeranoe also now includes AMF in the latest builds, so you have that option too.

**Comment by wokmi** [comment]
I spend two days to compile both FFMPEG and FFMPEG-amf builds....the hevc_amf output on the both build are not working properly so far...unlike hevc_nevc... the hevc output stream seems not perfectly fit to the mp4 container format...also the msys2 build relying on too many pacman packages(thus dozen of .dll files ) deceases the speed down by half comparing to the FFMPEG's static win build..

**Comment by Xaymar** [comment]
@wokmi You know you can just follow the ffmpeg guidelines for building now, right? This repo is purely used for updates to the AMF-only builds of ffmpeg.
